"""
Build the JSON data bundles consumed by the browser viewer.

Reads:
  data/processed/nmtc_projects.csv
  data/processed/nmtc_transactions.csv
  data/processed/headline.json
  data/cache/2020_Gaz_tracts_national.txt      (US Census 2020 tract gazetteer)

Writes (as <script>-includable JS files so the viewer works over file://):
  viewer/data/projects.js           window.NMTC_PROJECTS  — one row per project w/ lat/lon
  viewer/data/states.js             window.NMTC_STATES     — state-level aggregates
  viewer/data/headline.js           window.NMTC_HEADLINE   — headline numbers
  viewer/data/top_cdes.js           window.NMTC_TOP_CDES   — top 20 CDE table

If the gazetteer isn't found, downloads it from census.gov and caches it.
"""
import json
import urllib.request
import zipfile
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
IN = ROOT / "data" / "processed"
CACHE = ROOT / "data" / "cache"
OUT = ROOT / "viewer" / "data"
OUT.mkdir(parents=True, exist_ok=True)

GAZ_TXT = CACHE / "2020_Gaz_tracts_national.txt"
GAZ_URL = ("https://www2.census.gov/geo/docs/maps-data/data/gazetteer/"
           "2020_Gazetteer/2020_Gaz_tracts_national.zip")


def ensure_gazetteer():
    if GAZ_TXT.exists():
        return
    CACHE.mkdir(parents=True, exist_ok=True)
    zpath = CACHE / "gaz.zip"
    print(f"Downloading {GAZ_URL} ...")
    urllib.request.urlretrieve(GAZ_URL, zpath)
    with zipfile.ZipFile(zpath) as z:
        z.extractall(CACHE)
    zpath.unlink()


ensure_gazetteer()

# ---------------------------------------------------------------------------
# 1. Load tract centroids
# ---------------------------------------------------------------------------
gaz = pd.read_csv(GAZ_TXT, sep="\t", dtype={"GEOID": str})
gaz.columns = [c.strip() for c in gaz.columns]
gaz = gaz.rename(columns={
    "GEOID": "tract_fips",
    "INTPTLAT": "lat",
    "INTPTLONG": "lon",
    "USPS": "state_abbr",
})
gaz["tract_fips"] = gaz["tract_fips"].str.zfill(11)
gaz = gaz[["tract_fips", "state_abbr", "lat", "lon"]].copy()
print(f"Gazetteer: {len(gaz):,} tracts")

# ---------------------------------------------------------------------------
# 2. Load projects and merge
# ---------------------------------------------------------------------------
pr = pd.read_csv(IN / "nmtc_projects.csv")
# tract_fips arrived as int64; format as zero-padded 11-digit string
pr["tract_fips"] = pr["tract_fips"].astype("Int64").astype(str).str.zfill(11)

pr = pr.merge(gaz, on="tract_fips", how="left")
missing = pr["lat"].isna().sum()
print(f"Projects merged: {len(pr):,}, missing coords: {missing}")

# ---------------------------------------------------------------------------
# 3. Shrink + write projects.js (target ~500KB uncompressed JS literal)
# ---------------------------------------------------------------------------
slim = pr[[
    "project_id", "year", "metro", "qalicb_type",
    "state", "city",
    "project_qlici", "project_cost", "leverage_win",
    "lat", "lon",
]].copy()

# Round dollars to whole dollars; round lat/lon to 5 decimals (~1 m); round
# leverage to 3 decimals.  Small but real size win.
slim["project_qlici"] = slim["project_qlici"].round(0)
slim["project_cost"] = slim["project_cost"].round(0)
slim["leverage_win"] = slim["leverage_win"].round(3)
slim["lat"] = slim["lat"].round(5)
slim["lon"] = slim["lon"].round(5)

# Drop rows we can't plot
slim = slim.dropna(subset=["lat", "lon"]).reset_index(drop=True)
print(f"Projects with coords for viewer: {len(slim):,}")

records = slim.to_dict(orient="records")
# Replace NaN with None for clean JSON
import math
for r in records:
    for k, v in r.items():
        if isinstance(v, float) and math.isnan(v):
            r[k] = None

(OUT / "projects.js").write_text(
    "// auto-generated by scripts/build_viewer_data.py — do not edit by hand\n"
    "window.NMTC_PROJECTS = " + json.dumps(records, separators=(",", ":")) + ";\n"
)
size_kb = (OUT / "projects.js").stat().st_size / 1024
print(f"Wrote projects.js  ({size_kb:.1f} KB, {len(records):,} records)")

# ---------------------------------------------------------------------------
# 4. State-level aggregates
# ---------------------------------------------------------------------------
state_agg = (
    pr.groupby("state").agg(
        n_projects=("project_id", "count"),
        qlici_total=("project_qlici", "sum"),
        cost_total=("project_cost", "sum"),
        n_non_metro=("metro", lambda s: int((s == "non_metro").sum())),
        lev_median=("leverage_win", "median"),
    ).reset_index()
)
state_agg["non_metro_share"] = (
    state_agg["n_non_metro"] / state_agg["n_projects"]
).round(3)
state_agg["qlici_total_m"] = (state_agg["qlici_total"] / 1e6).round(1)
state_agg["cost_total_m"] = (state_agg["cost_total"] / 1e6).round(1)
state_agg["mobilization_ratio"] = (
    (state_agg["cost_total"] - state_agg["qlici_total"]) / state_agg["qlici_total"]
).round(3)
state_agg["lev_median"] = state_agg["lev_median"].round(3)

state_cols = ["state", "n_projects", "qlici_total_m", "cost_total_m",
              "non_metro_share", "lev_median", "mobilization_ratio"]
state_records = state_agg[state_cols].to_dict(orient="records")
(OUT / "states.js").write_text(
    "window.NMTC_STATES = " + json.dumps(state_records, separators=(",", ":")) + ";\n"
)
print(f"Wrote states.js   ({len(state_records)} states)")

# ---------------------------------------------------------------------------
# 5. Headline numbers
# ---------------------------------------------------------------------------
headline = json.loads((IN / "headline.json").read_text())
(OUT / "headline.js").write_text(
    "window.NMTC_HEADLINE = " + json.dumps(headline, indent=2) + ";\n"
)
print("Wrote headline.js")

# ---------------------------------------------------------------------------
# 6. Top CDEs table
# ---------------------------------------------------------------------------
top = pd.read_csv(IN / "top_cdes.csv").to_dict(orient="records")
(OUT / "top_cdes.js").write_text(
    "window.NMTC_TOP_CDES = " + json.dumps(top, separators=(",", ":")) + ";\n"
)
print(f"Wrote top_cdes.js ({len(top)} rows)")

print("\nAll viewer data bundles ready → viewer/data/")
