"""
Build paper/tables/rehab.tex from the rehabilitation-cell verification.

Reads:  data/processed/regressions/rehab_cell_verification.json
Writes: paper/tables/rehab.tex

Run:    python3 scripts/make_rehab_table.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REG = ROOT / "data" / "processed" / "regressions"
TAB = ROOT / "paper" / "tables"

def sci(x: float) -> str:
    """LaTeX scientific notation. f"{x:.1e}" renders as 1.6e-05 in math
    mode, which is not how a p-value is set."""
    mant, exp = f"{x:.1e}".split("e")
    return f"{mant} \\times 10^{{{int(exp)}}}"


R = json.loads((REG / "rehab_cell_verification.json").read_text())
r1, r2, r3 = R["R1"], R["R2_outcome_variants"], R["R3_influence"]
r4, r5, r6 = R["R4_randomization"], R["R5_wild_cluster"], R["R6_other_purposes"]

PRETTY_VARIANT = {
    "winsor_1_20 (baseline)": "Winsorized $[1,20]$ (baseline)",
    "unwinsorized": "Unwinsorized",
    "log": "Log outcome",
    "winsor_1_10": "Winsorized $[1,10]$",
    "winsor_1_50": "Winsorized $[1,50]$",
}
PRETTY_PURPOSE = {
    "business": "Business financing",
    "re_construction": "Real estate, construction",
}

lines = [
    "% Generated by scripts/make_rehab_table.py. Do not edit.",
    "\\begin{tabular}{@{}llr@{}}",
    "\\toprule",
    "Check & Specification or statistic & Result \\\\",
    "\\midrule",
    f"Baseline & $\\hat\\beta_{{\\text{{rural}}}}$ (CDE-clustered SE) & "
    f"${r1['beta']:+.4f}$ $({r1['se_cde_cluster']:.4f})$ \\\\",
    f" & $t$ statistic & ${r1['t']:+.2f}$ \\\\",
    f" & $p$-value & ${sci(r1['p_exact'])}$ \\\\",
    "\\midrule",
]
first = True
for key, v in r2.items():
    label = "Outcome" if first else ""
    first = False
    lines.append(f"{label} & {PRETTY_VARIANT.get(key, key)} & "
                 f"${v['beta']:+.4f}$ $({v['se']:.4f})$ \\\\")
lines += [
    "\\midrule",
    f"Influence & Leave one CDE out ({r3['n_cde_dropped_tested']} drops) & "
    f"$[{r3['leave_one_cde_min']:+.3f},\\ {r3['leave_one_cde_max']:+.3f}]$ \\\\",
    f" & Leave one state out & "
    f"$[{r3['leave_one_state_min']:+.3f},\\ {r3['leave_one_state_max']:+.3f}]$ \\\\",
    "\\midrule",
    f"Inference & Randomization, {r4['draws']:,} draws & "
    f"$p = {r4['p_two_sided']:.4f}$ \\\\",
    f" & Wild cluster bootstrap-$t$, {r5['draws']:,} draws & "
    f"$p = {r5['p_two_sided']:.4f}$ \\\\",
    "\\midrule",
]
first = True
for key, v in r6.items():
    if not v.get("estimated"):
        continue
    label = "Placebo purposes" if first else ""
    first = False
    lines.append(f"{label} & {PRETTY_PURPOSE.get(key, key)} & "
                 f"${v['beta']:+.4f}$ $({v['se']:.4f})$ \\\\")
lines += ["\\bottomrule", "\\end{tabular}"]

TAB.mkdir(parents=True, exist_ok=True)
(TAB / "rehab.tex").write_text("\n".join(lines) + "\n")
print(f"wrote {TAB/'rehab.tex'}")
