"""
Build paper/tables/purpose.tex from the purpose channel run.

Reads:  data/processed/regressions/purpose_channel.json
Writes: paper/tables/purpose.tex

Run:    python3 scripts/make_purpose_table.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REG = ROOT / "data" / "processed" / "regressions"
TAB = ROOT / "paper" / "tables"

R = json.loads((REG / "purpose_channel.json").read_text())
L, G = R["ladder"], R["gelbach_with_purpose"]

PRETTY = {
    "business": "Business financing",
    "re_construction": "Real estate, construction",
    "re_rehab": "Real estate, rehabilitation",
    "housing_sf_new": "Housing, single family, new",
    "other": "Other financing purpose",
    "other_small": "Folded rare categories",
}

lines = [
    "% Generated by scripts/make_purpose_table.py. Do not edit.",
    "\\begin{tabular}{@{}lrrr@{}}",
    "\\multicolumn{4}{@{}l}{\\textit{Panel A. Composition and leverage by purpose}} \\\\[2pt]",
    "\\toprule",
    "Purpose & Projects & Median lev. & \\% rural \\\\",
    "\\midrule",
]
for key, lev in sorted(R["leverage_by_purpose"].items(),
                       key=lambda kv: -kv[1]["n"]):
    comp = R["composition_by_rural_pct"].get(key, {"rural": 0.0})
    lines.append(f"{PRETTY.get(key, key)} & {lev['n']:,} & "
                 f"{lev['median']:.3f} & {comp['rural']:.1f}\\% \\\\")
lines += [
    "\\bottomrule",
    "\\end{tabular}",
    "",
    "\\vspace{1.1em}",
    "",
    "\\begin{tabular}{@{}lrr@{}}",
    "\\multicolumn{3}{@{}l}{\\textit{Panel B. The rural coefficient with purpose inserted}} \\\\[2pt]",
    "\\toprule",
    "Specification & $\\hat\\beta_{\\text{rural}}$ & (SE) \\\\",
    "\\midrule",
]
ROWS = [
    ("Raw", "M0_raw"),
    ("Year", "M1_year"),
    ("Year, QALICB type", "M2_year_type"),
    ("Year, purpose", "M2b_year_purpose"),
    ("Year, type, purpose", "M3_year_type_purpose"),
    ("Year, type, purpose, state", "M4_year_type_purpose_state"),
    ("Year, type, CDE", "M5_within_cde_no_purpose"),
    ("Year, type, purpose, CDE", "M6_within_cde_with_purpose"),
]
for label, key in ROWS:
    v = L[key]
    lines.append(f"{label} & ${v['beta']:+.4f}$ & $({v['se']:.4f})$ \\\\")
lines += [
    "\\bottomrule",
    "\\end{tabular}",
    "",
    "\\vspace{1.1em}",
    "",
    "\\begin{tabular}{@{}lrr@{}}",
    "\\multicolumn{3}{@{}l}{\\textit{Panel C. Order-invariant decomposition, purpose as a fourth block}} \\\\[2pt]",
    "\\toprule",
    "Block & Contribution & Share \\\\",
    "\\midrule",
]
tot = G["total_explained"]
for label, key in [("Origination year", "contrib_year"),
                   ("QALICB type", "contrib_qalicb"),
                   ("Purpose of investment", "contrib_purpose"),
                   ("CDE identity", "contrib_cde")]:
    c = G[key]
    lines.append(f"{label} & ${c:+.4f}$ & ${100*c/tot:.1f}\\%$ \\\\")
lines += [
    "\\midrule",
    f"Total explained & ${tot:+.4f}$ & \\\\",
    "\\bottomrule",
    "\\end{tabular}",
]

TAB.mkdir(parents=True, exist_ok=True)
(TAB / "purpose.tex").write_text("\n".join(lines) + "\n")
print(f"wrote {TAB/'purpose.tex'}")
