"""
Build paper/tables/residual.tex from the residual scan.

This table was previously maintained by hand, which is how it came to be
out of step with the scan when purpose-of-investment cells were added.

Reads:  data/processed/regressions/residual_analysis.json
Writes: paper/tables/residual.tex

Run:    python3 scripts/make_residual_table.py
"""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REG = ROOT / "data" / "processed" / "regressions"
TAB = ROOT / "paper" / "tables"

R = json.loads((REG / "residual_analysis.json").read_text())

PRETTY_PURPOSE = {
    "business": "Business financing",
    "re_construction": "Real estate, construction",
    "re_rehab": "Real estate, rehabilitation",
    "housing_sf_new": "Housing, single family, new",
    "other": "Other financing purpose",
    "other_small": "Folded rare categories",
}


def label(cell: str) -> str:
    """LaTeX-safe, readable cell label."""
    if cell.startswith("purpose "):
        key = cell.split(" ", 1)[1]
        return "Purpose: " + PRETTY_PURPOSE.get(key, key.replace("_", " "))
    out = cell
    out = out.replace("<=", "$\\leq$").replace("inf", "$\\infty$")
    out = re.sub(r"(?<![$\\])<", "$<$", out)
    out = out.replace("%", "\\%")
    return out[0].upper() + out[1:]


lines = [
    "% Generated by scripts/make_residual_table.py. Do not edit.",
    "{\\footnotesize\\setlength{\\tabcolsep}{4pt}",
    "\\begin{tabular}{lrrrrrc}",
    "\\toprule",
    " & $\\hat\\beta$ & (SE) & $p$ & $N$ & switchers & BH 5\\% \\\\",
    "\\midrule",
]
for c in R["cells"]:
    lab = label(c["cell"])
    if not c["estimated"]:
        lines.append(f"{lab} & \\multicolumn{{3}}{{c}}{{\\itshape not estimated}} "
                     f"& {c['n']:,} & {c['n_switcher_cde']} & \\\\")
        continue
    p = c["p"]
    p_txt = "$<$0.001" if p < 0.001 else f"{p:.2f}"
    lines.append(
        f"{lab} & {c['beta']:.3f} & ({c['se']:.3f}) & {p_txt} & "
        f"{c['n']:,} & {c['n_switcher_cde']} & "
        f"{'\\textbf{yes}' if c['bh_reject_at_05'] else 'no'} \\\\")
lines += ["\\bottomrule", "\\end{tabular}}"]

TAB.mkdir(parents=True, exist_ok=True)
(TAB / "residual.tex").write_text("\n".join(lines) + "\n")
print(f"wrote {TAB/'residual.tex'} with {len(R['cells'])} cells "
      f"({R['n_significant_after_bh']} surviving BH)")
