"""
Build paper/tables/median_inference.tex from the median inference run.

Kept separate from make_paper_tables.py so that re-running the expensive
bootstrap does not require regenerating every other table in the paper.

Reads:  data/processed/regressions/median_inference.json
Writes: paper/tables/median_inference.tex

Run:    python3 scripts/make_median_inference_table.py
"""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REG = ROOT / "data" / "processed" / "regressions"
TAB = ROOT / "paper" / "tables"

R = json.loads((REG / "median_inference.json").read_text())

rows = [
    ("Point estimate, within-CDE rural coefficient",
     f"${R['point_estimate']:+.4f}$"),
    ("Asymptotic standard error (quantile regression)",
     f"${R['se_asymptotic']:.4f}$"),
    (f"CDE-cluster bootstrap standard error ({R['b_bootstrap_used']} reps)",
     f"${R['se_cluster_bootstrap']:.4f}$"),
    ("Inflation from clustering",
     f"${R['se_inflation_vs_asymptotic']:.2f}\\times$"),
    ("Bootstrap percentile 95\\% interval",
     f"$[{R['bootstrap_ci95_percentile'][0]:+.3f},\\ "
     f"{R['bootstrap_ci95_percentile'][1]:+.3f}]$"),
    ("Rejectable penalty, asymptotic",
     f"${R['equivalence_bound_asymptotic']:.3f}$"),
    ("Rejectable penalty, clustered",
     f"${R['equivalence_bound_cluster_bootstrap']:.3f}$"),
    (f"Randomization inference, two-sided $p$ ({R['b_permutation_used']} draws)",
     f"${R['randomization_p_two_sided']:.3f}$"),
    ("Permutations pinned to a vertex",
     f"${100 * R['randomization_share_pinned_at_zero']:.0f}\\%$"),
    (f"Paired within-CDE median gap ({R['paired_n_switchers']} intermediaries)",
     f"${R['paired_median_difference']:+.3f}$"),
    ("Wilcoxon signed-rank $p$ on the paired gaps",
     f"${R['wilcoxon_p']:.3f}$"),
]

lines = [
    "% Generated by scripts/make_median_inference_table.py. Do not edit.",
    "\\begin{tabular}{@{}lr@{}}",
    "\\toprule",
    "& \\multicolumn{1}{c}{Value} \\\\",
    "\\midrule",
]
for label, value in rows:
    lines.append(f"{label} & {value} \\\\")
lines += ["\\bottomrule", "\\end{tabular}"]

TAB.mkdir(parents=True, exist_ok=True)
(TAB / "median_inference.tex").write_text("\n".join(lines) + "\n")
print(f"wrote {TAB/'median_inference.tex'} with {len(rows)} rows")
